"""ISKG — IFAZ Widget Toolkit.

A Python widget framework with tactical IFAZ theme, rendering widgets
as HTML/CSS/JS inside a native window via pywebview.
"""

from ._version import VERSION

__version__ = VERSION
from .app import Application, Window
from .base import Widget
from .vars import BooleanVar, DoubleVar, IntVar, StringVar, Variable
from .widgets import (
    Button,
    Canvas,
    CheckBox,
    ComboBox,
    DataGrid,
    DropTarget,
    Entry,
    FileDialog,
    Frame,
    IconLabel,
    ImageBox,
    IndicatorLED,
    Knob,
    Label,
    LEDDisplay,
    ListBox,
    Menu,
    MenuBar,
    MessageDialog,
    Notebook,
    PanedWindow,
    ProgressBar,
    RadialGauge,
    RadioButton,
    RichText,
    Scale,
    ScrollBar,
    ScrolledFrame,
    Separator,
    Slider,
    Spacer,
    SpinBox,
    StatusBar,
    Text,
    ToggleSwitch,
    Tooltip,
    TreeView,
    showerror,
    showinfo,
    showquestion,
    showwarning,
)

__all__ = [
    "VERSION",
    "Widget",
    "Label",
    "Button",
    "Entry",
    "CheckBox",
    "RadioButton",
    "ComboBox",
    "Slider",
    "ProgressBar",
    "Frame",
    "ScrolledFrame",
    "PanedWindow",
    "ListBox",
    "ScrollBar",
    "Text",
    "SpinBox",
    "Separator",
    "Notebook",
    "Canvas",
    "Scale",
    "MessageDialog",
    "Knob",
    "LEDDisplay",
    "DataGrid",
    "IndicatorLED",
    "RadialGauge",
    "ToggleSwitch",
    "StatusBar",
    "Tooltip",
    "Spacer",
    "ImageBox",
    "IconLabel",
    "RichText",
    "TreeView",
    "DropTarget",
    "Menu",
    "MenuBar",
    "FileDialog",
    "Variable",
    "StringVar",
    "IntVar",
    "DoubleVar",
    "BooleanVar",
    "showinfo",
    "showwarning",
    "showerror",
    "showquestion",
    "Application",
    "Window",
]
